apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  namespace: node-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: catayflux.azurecr.io/catay-hello-world:cdf9a35f727d8bc6e0ef3b11b815ca9899fa0d93
        resources:
          requests:
            cpu: 125m
            memory: 128Mi
        ports:
        - containerPort: 3000
